# Generated by Django 6.0.4 on 2026-05-03 06:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('coop', 'Cooperative'), ('admin', 'Admin')], max_length=20)),
                ('sub_role', models.CharField(blank=True, choices=[('exportateur', 'Exportateur'), ('importateur', 'Importateur'), ('transformateur', 'Transformateur')], max_length=20, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=20)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.CharField(help_text='ex: 2025-2026', max_length=50)),
                ('crop_type', models.CharField(choices=[('cacao', 'Cacao'), ('café', 'Café')], max_length=20)),
                ('estimated_quantity', models.FloatField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('unique_code', models.CharField(help_text='format TRC-YYYY-XXXX', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='api.batch')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validated_batch_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('batch', 'Batch'), ('validation', 'Validation'), ('transaction', 'Transaction'), ('transformation', 'Transformation'), ('transport', 'Transport')], max_length=50)),
                ('entity_id', models.UUIDField(help_text="ID de l'entité concernée")),
                ('hash', models.CharField(help_text="SHA-256 des données de l'entité", max_length=255)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('chain', models.CharField(blank=True, max_length=100, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('anchored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='idx_bc_entity'), models.Index(fields=['tx_hash'], name='idx_bc_tx_hash'), models.Index(fields=['hash'], name='idx_bc_hash')],
            },
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_document', models.FileField(blank=True, null=True, upload_to='cooperatives/docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cooperatives', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_cooperatives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoopAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('inspecteur', 'Inspecteur'), ('agent_terrain', 'Agent de terrain')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coop_agent_roles', to=settings.AUTH_USER_MODEL)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='api.cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='CoopMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='gestionnaire', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.cooperative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coop_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('harvest_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='api.batch')),
            ],
        ),
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cni_front_image', models.ImageField(upload_to='kyc/cni/')),
                ('cni_back_image', models.ImageField(upload_to='kyc/cni/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_kycs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('validation', 'Validation'), ('rejection', 'Rejection'), ('transaction', 'Transaction'), ('transport', 'Transport'), ('fraud', 'Fraud'), ('transformation', 'Transformation'), ('security', 'Security'), ('system', 'System')], max_length=50)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gps_coordinates', models.JSONField(help_text='JSON polygon — minimum 3 points')),
                ('area', models.FloatField(blank=True, help_text='Calculé automatiquement en hectares', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_parcels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('gps_conflict', 'GPS Conflict'), ('duplicate', 'Duplicate'), ('anomaly', 'Anomaly'), ('multi_account', 'Multi Account'), ('production_excess', 'Production Excess'), ('transport_anomaly', 'Transport Anomaly'), ('transformation_anomaly', 'Transformation Anomaly')], max_length=50)),
                ('score', models.FloatField(help_text='0-100 — 70+ = élevé')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('resolution_comment', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='api.batch')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_frauds', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='api.parcel')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.parcel'),
        ),
        migrations.CreateModel(
            name='ParcelValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspected_parcels', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='api.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='api.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create_farmer', 'Create Farmer'), ('create_parcel', 'Create Parcel'), ('create_batch', 'Create Batch'), ('harvest', 'Harvest'), ('kyc_capture', 'KYC Capture')], max_length=50)),
                ('payload', models.JSONField()),
                ('local_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('conflict_reason', models.TextField(blank=True, null=True)),
                ('created_locally_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TraceabilityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('validate', 'Validate'), ('reject', 'Reject'), ('harvest', 'Harvest'), ('transport', 'Transport'), ('transform', 'Transform'), ('sell', 'Sell'), ('fraud_alert', 'Fraud Alert'), ('field_activity', 'Field Activity')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_logs', to='api.batch')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.batch')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_type', models.CharField(choices=[('self', 'Self'), ('third_party', 'Third Party')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transformations', to=settings.AUTH_USER_MODEL)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_transformations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransformationInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_transformations', to='api.batch')),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='api.transformation')),
            ],
        ),
        migrations.CreateModel(
            name='TransformationOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_by_transformations', to='api.batch')),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='api.transformation')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_transports', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='api.batch')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_type', models.CharField(choices=[('transporteur', 'Transporteur'), ('transformateur', 'Transformateur')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_assignments', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_assignments', to=settings.AUTH_USER_MODEL)),
                ('transformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_assignments', to='api.transformation')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_assignments', to='api.transport')),
            ],
        ),
        migrations.CreateModel(
            name='TransporterRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active')], default='invited', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_transporters', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='transporter_registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='api.transporterregistry'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='idx_users_role_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='idx_users_phone'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email'),
        ),
        migrations.AddIndex(
            model_name='batchvalidation',
            index=models.Index(fields=['batch'], name='idx_batch_val_batch'),
        ),
        migrations.AddIndex(
            model_name='cooperative',
            index=models.Index(fields=['user'], name='idx_coop_user_id'),
        ),
        migrations.AddIndex(
            model_name='cooperative',
            index=models.Index(fields=['status'], name='idx_coop_status'),
        ),
        migrations.AddIndex(
            model_name='coopagent',
            index=models.Index(fields=['cooperative'], name='idx_coop_agents_coop'),
        ),
        migrations.AlterUniqueTogether(
            name='coopagent',
            unique_together={('cooperative', 'user')},
        ),
        migrations.AddIndex(
            model_name='coopmember',
            index=models.Index(fields=['cooperative'], name='idx_coop_members_coop'),
        ),
        migrations.AddIndex(
            model_name='coopmember',
            index=models.Index(fields=['user'], name='idx_coop_members_user'),
        ),
        migrations.AlterUniqueTogether(
            name='coopmember',
            unique_together={('cooperative', 'user')},
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['batch'], name='idx_harvests_batch'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['harvest_date'], name='idx_harvests_date'),
        ),
        migrations.AddIndex(
            model_name='kycrecord',
            index=models.Index(fields=['user'], name='idx_kyc_user_id'),
        ),
        migrations.AddIndex(
            model_name='kycrecord',
            index=models.Index(fields=['status'], name='idx_kyc_status'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='idx_notif_user_unread'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='idx_notif_created'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['farmer'], name='idx_parcels_farmer'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status'], name='idx_parcels_status'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['user'], name='idx_fraud_user'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['batch'], name='idx_fraud_batch'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['parcel'], name='idx_fraud_parcel'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['status'], name='idx_fraud_status'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['status', 'score'], name='idx_fraud_status_score'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['farmer'], name='idx_batches_farmer'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['parcel'], name='idx_batches_parcel'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status'], name='idx_batches_status'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('parcel', 'season', 'crop_type')},
        ),
        migrations.AddIndex(
            model_name='parcelvalidation',
            index=models.Index(fields=['parcel'], name='idx_parcel_val_parcel'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['batch'], name='idx_qr_batch'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'is_active'], name='idx_sessions_user_active'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['expires_at'], name='idx_sessions_expires'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['agent'], name='idx_sync_agent'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['status'], name='idx_sync_status'),
        ),
        migrations.AlterUniqueTogether(
            name='syncqueue',
            unique_together={('agent', 'local_id')},
        ),
        migrations.AddIndex(
            model_name='traceabilitylog',
            index=models.Index(fields=['batch'], name='idx_trace_batch'),
        ),
        migrations.AddIndex(
            model_name='traceabilitylog',
            index=models.Index(fields=['action_type'], name='idx_trace_action'),
        ),
        migrations.AddIndex(
            model_name='traceabilitylog',
            index=models.Index(fields=['performed_by'], name='idx_trace_performer'),
        ),
        migrations.AddIndex(
            model_name='traceabilitylog',
            index=models.Index(fields=['created_at'], name='idx_trace_created'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['batch'], name='idx_transactions_batch'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer'], name='idx_transactions_buyer'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller'], name='idx_transactions_seller'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='idx_transactions_status'),
        ),
        migrations.AddIndex(
            model_name='transformation',
            index=models.Index(fields=['created_by'], name='idx_transfo_creator'),
        ),
        migrations.AddIndex(
            model_name='transformation',
            index=models.Index(fields=['transformer'], name='idx_transfo_transformer'),
        ),
        migrations.AddIndex(
            model_name='transformationinput',
            index=models.Index(fields=['transformation'], name='idx_transfo_inputs_transfo'),
        ),
        migrations.AlterUniqueTogether(
            name='transformationinput',
            unique_together={('transformation', 'batch')},
        ),
        migrations.AddIndex(
            model_name='transformationoutput',
            index=models.Index(fields=['transformation'], name='idx_transfo_outputs_transfo'),
        ),
        migrations.AlterUniqueTogether(
            name='transformationoutput',
            unique_together={('transformation', 'batch')},
        ),
        migrations.AddIndex(
            model_name='operatorassignment',
            index=models.Index(fields=['operator'], name='idx_op_assign_operator'),
        ),
        migrations.AddIndex(
            model_name='operatorassignment',
            index=models.Index(fields=['transport'], name='idx_op_assign_transport'),
        ),
        migrations.AddIndex(
            model_name='operatorassignment',
            index=models.Index(fields=['transformation'], name='idx_op_assign_transformation'),
        ),
        migrations.AddIndex(
            model_name='transporterregistry',
            index=models.Index(fields=['phone'], name='idx_transporter_phone'),
        ),
        migrations.AddIndex(
            model_name='transporterregistry',
            index=models.Index(fields=['user'], name='idx_transporter_user'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['batch'], name='idx_transports_batch'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['transporter_registry'], name='idx_transports_transporter'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['status'], name='idx_transports_status'),
        ),
    ]
