# Generated by Django 6.0.4 on 2026-05-10 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_document', models.FileField(blank=True, null=True, upload_to='stores/docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('inspecteur', 'Inspecteur'), ('agent_terrain', 'Agent de terrain')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='gestionnaire', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coopagent',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='coopagent',
            name='idx_coop_agents_coop',
        ),
        migrations.RemoveIndex(
            model_name='cooperative',
            name='idx_coop_user_id',
        ),
        migrations.RemoveIndex(
            model_name='cooperative',
            name='idx_coop_status',
        ),
        migrations.AlterUniqueTogether(
            name='coopmember',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='coopmember',
            name='idx_coop_members_coop',
        ),
        migrations.RemoveIndex(
            model_name='coopmember',
            name='idx_coop_members_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('store', 'Store'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeagent',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='api.store'),
        ),
        migrations.AddField(
            model_name='storeagent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_agent_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storemember',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.store'),
        ),
        migrations.AddField(
            model_name='storemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='coopagent',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='coopagent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='coopmember',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='coopmember',
            name='user',
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['user'], name='idx_store_user_id'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status'], name='idx_store_status'),
        ),
        migrations.AddIndex(
            model_name='storeagent',
            index=models.Index(fields=['store'], name='idx_store_agents_store'),
        ),
        migrations.AlterUniqueTogether(
            name='storeagent',
            unique_together={('store', 'user')},
        ),
        migrations.AddIndex(
            model_name='storemember',
            index=models.Index(fields=['store'], name='idx_store_members_store'),
        ),
        migrations.AddIndex(
            model_name='storemember',
            index=models.Index(fields=['user'], name='idx_store_members_user'),
        ),
        migrations.AlterUniqueTogether(
            name='storemember',
            unique_together={('store', 'user')},
        ),
        migrations.DeleteModel(
            name='CoopAgent',
        ),
        migrations.DeleteModel(
            name='Cooperative',
        ),
        migrations.DeleteModel(
            name='CoopMember',
        ),
    ]
