# Generated by Django 6.0.4 on 2026-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_store_storeagent_storemember_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
