# Generated by Django 6.0.5 on 2026-05-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_otp_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='export_license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='import_license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
