# Generated by Django 6.0.4 on 2026-05-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_export_license_user_import_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('store', 'Store'), ('agent', 'Agent'), ('transporter', 'Transporter'), ('processor', 'Processor'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_role',
            field=models.CharField(blank=True, choices=[('exportateur', 'Exportateur'), ('importateur', 'Importateur'), ('transformateur', 'Transformateur'), ('inspector', 'Inspecteur')], max_length=20, null=True),
        ),
    ]
