# Generated by Django 6.0.4 on 2026-05-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_role_alter_user_sub_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
