# Generated by Django 6.0.4 on 2026-05-15 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_otprecord_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='api.store'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='api.store'),
        ),
    ]
