# Generated by Django 6.0.5 on 2026-05-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_batch_store_parcel_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_role',
            field=models.CharField(blank=True, choices=[('exportateur', 'Exportateur'), ('importateur', 'Importateur'), ('transformateur', 'Transformateur'), ('inspector', 'Inspecteur'), ('super_admin', 'Super Admin'), ('gouvernement', 'Gouvernement'), ('certificateur', 'Certificateur')], max_length=20, null=True),
        ),
    ]
